// <auto-generated />
using System;
using Envora.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Envora.Api.Data.Migrations
{
    [DbContext(typeof(EnvoraDbContext))]
    [Migration("20251218223027_InitialSchema_v3_0")]
    partial class InitialSchema_v3_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Envora.Api.Data.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActivityId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_activitylogs_project");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs", "dbo");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CompanyId");

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("Companies", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Companies_Type", "[Type] IN ('Customer','Vendor','Engineer','Contractor')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Controller", b =>
                {
                    b.Property<Guid>("ControllerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AnalogInputCount")
                        .HasColumnType("int");

                    b.Property<int?>("AnalogOutputCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CommissioningDate")
                        .HasColumnType("date");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ControllerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DigitalInputCount")
                        .HasColumnType("int");

                    b.Property<int?>("DigitalOutputCount")
                        .HasColumnType("int");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly?>("WarrantyExpirationDate")
                        .HasColumnType("date");

                    b.HasKey("ControllerId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_controllers_project");

                    b.HasIndex("ProjectId", "ControllerName")
                        .IsUnique();

                    b.ToTable("Controllers", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Controllers_ControllerType", "[ControllerType] IN ('VAVController','BMS','PLC','RTU','Thermostat','VFD','Gateway','Other')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.ControllerIoSlot", b =>
                {
                    b.Property<Guid>("IOSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IOType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SlotNumber")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("IOSlotId");

                    b.HasIndex("AssignedPointId");

                    b.HasIndex("ControllerId")
                        .HasDatabaseName("idx_ioslots_controller");

                    b.HasIndex("IsUsed")
                        .HasDatabaseName("idx_ioslots_used");

                    b.HasIndex("ControllerId", "SlotName")
                        .IsUnique();

                    b.ToTable("ControllerIOSlots", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_ControllerIOSlots_IOType", "[IOType] IN ('AI','AO','DI','DO')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.DamperScheduleItem", b =>
                {
                    b.Property<Guid>("DamperScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActuatorType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DamperTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Pressure")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("DamperScheduleId");

                    b.HasIndex("ProjectId", "DamperTag")
                        .IsUnique();

                    b.ToTable("DamperSchedule", "dbo");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Deliverable", b =>
                {
                    b.Property<Guid>("DeliverableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ApprovedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliverableType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("SubmittedDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("DeliverableId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_deliverables_project");

                    b.ToTable("Deliverables", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Deliverables_DeliverableType", "[DeliverableType] IN ('Submittal','IOM','AsBuilt','CommissioningReport')");

                            t.HasCheckConstraint("CK_Deliverables_Status", "[Status] IS NULL OR [Status] IN ('NotStarted','InProgress','Ready','Submitted','ApprovedWithChanges','Approved','Rejected','Archived')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("CommissioningDate")
                        .HasColumnType("date");

                    b.Property<string>("CommissioningStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DatasheetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<string>("IomUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("IOMUrl");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("MountedOnEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhysicalProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectSpecificSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("WiringDiagramUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DeviceId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeviceType")
                        .HasDatabaseName("idx_devices_type");

                    b.HasIndex("MountedOnEquipmentId")
                        .HasDatabaseName("idx_devices_equipment");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_devices_project");

                    b.HasIndex("ProjectId", "DeviceName")
                        .IsUnique();

                    b.ToTable("Devices", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Devices_CommissioningStatus", "[CommissioningStatus] IS NULL OR [CommissioningStatus] IN ('NotStarted','InProgress','Commissioned','Verified','Failed')");

                            t.HasCheckConstraint("CK_Devices_DeviceType", "[DeviceType] IN ('Relay','Enclosure','Terminal','Transformer','Wiring','Thermistor','RTD','Sensor','Actuator','Transducer','Valve','Damper','FlowMeter','UtilityMeter','AirflowStation','Other')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Equipment", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Capacity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CapacityUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaintenanceFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecSheetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly?>("WarrantyExpirationDate")
                        .HasColumnType("date");

                    b.HasKey("EquipmentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EquipmentType")
                        .HasDatabaseName("idx_equipment_type");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_equipment_project");

                    b.HasIndex("ProjectId", "EquipmentTag")
                        .IsUnique();

                    b.ToTable("Equipment", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Equipment_EquipmentType", "[EquipmentType] IN ('RTU','AHU','VAV','Pump','Fan','Chiller','Boiler','Damper','Valve','Sensor','Other')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Queued");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("JobId");

                    b.HasIndex("JobType")
                        .HasDatabaseName("idx_jobs_type");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("idx_jobs_project_status");

                    b.ToTable("Jobs", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Jobs_JobType", "[JobType] IN ('GenerateSubmittal','VisioExport','PDFGeneration','EquipmentSchedule','BOMGeneration','Other')");

                            t.HasCheckConstraint("CK_Jobs_Status", "[Status] IN ('Queued','Processing','Completed','Failed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Node", b =>
                {
                    b.Property<Guid>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusAssociation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("CommissioningDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxDevices")
                        .HasColumnType("int");

                    b.Property<string>("NetworkAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Protocol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("NodeId");

                    b.HasIndex("ControllerId")
                        .HasDatabaseName("idx_nodes_controller");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_nodes_project");

                    b.HasIndex("Protocol")
                        .HasDatabaseName("idx_nodes_protocol");

                    b.HasIndex("ControllerId", "NodeName")
                        .IsUnique();

                    b.ToTable("Nodes", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Nodes_NodeType", "[NodeType] IN ('BACnetMSTP','BACnetIP','ModbusTCP','ModbusRTU','TCPIPGateway','EthernetInterface','SerialInterface','Other')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discipline")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MentionedUserIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentNoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("NoteId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentNoteId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("ProjectId", "Discipline")
                        .HasDatabaseName("idx_notes_project_discipline");

                    b.ToTable("Notes", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Notes_Discipline", "[Discipline] IS NULL OR [Discipline] IN ('Overview','Financial','Schedule','Design','Service')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.NoteReaction", b =>
                {
                    b.Property<Guid>("ReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReactionId");

                    b.HasIndex("UserId");

                    b.HasIndex("NoteId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("NoteReactions", "dbo");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Point", b =>
                {
                    b.Property<Guid>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BACnetObjectInstance")
                        .HasColumnType("int");

                    b.Property<string>("BACnetObjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ControlPriority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ControllerIOSlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ControllerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsLogged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsMonitored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsMultiTermination")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MaxPhysical")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MaxRaw")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinPhysical")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinRaw")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Offset")
                        .HasColumnType("decimal(10,4)");

                    b.Property<Guid?>("ParentDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PointDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PointTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PointType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Quality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ScalingFactor")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("PointId");

                    b.HasIndex("ControllerIOSlotId");

                    b.HasIndex("ControllerId")
                        .HasDatabaseName("idx_points_controller");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("idx_points_device");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("idx_points_equipment");

                    b.HasIndex("IsMultiTermination")
                        .HasDatabaseName("idx_points_multiterm");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_points_project");

                    b.HasIndex("SourceType")
                        .HasDatabaseName("idx_points_source");

                    b.HasIndex("ProjectId", "PointTag")
                        .IsUnique();

                    b.ToTable("Points", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Points_ControlPriority", "[ControlPriority] IS NULL OR [ControlPriority] IN ('Manual','Auto','Locked','Override')");

                            t.HasCheckConstraint("CK_Points_DataType", "[DataType] IN ('AnalogInput','AnalogOutput','DigitalInput','DigitalOutput','Integer','Real','String','Enumeration')");

                            t.HasCheckConstraint("CK_Points_PointType", "[PointType] IN ('Input','Output','Variable','Parameter')");

                            t.HasCheckConstraint("CK_Points_SourceType", "[SourceType] IN ('SoftPoint','HardPoint')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.PointDistribution", b =>
                {
                    b.Property<Guid>("DistributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsumingControllerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("LocalPointName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SoftPointId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DistributionId");

                    b.HasIndex("ConsumingControllerId")
                        .HasDatabaseName("idx_distribution_consumer");

                    b.HasIndex("NodeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SoftPointId")
                        .HasDatabaseName("idx_distribution_soft");

                    b.HasIndex("SoftPointId", "ConsumingControllerId")
                        .IsUnique();

                    b.ToTable("PointDistribution", "dbo");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ActualCompletion")
                        .HasColumnType("date");

                    b.Property<decimal?>("BudgetAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("BuildingType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DesignEngineer1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DesignEngineer2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EngineeringFirmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EstimatedCompletion")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SquareFootage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ProjectId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DesignEngineer1Id");

                    b.HasIndex("DesignEngineer2Id");

                    b.HasIndex("EngineeringFirmId");

                    b.HasIndex("ProjectManagerId")
                        .HasDatabaseName("idx_projects_pm");

                    b.HasIndex("ProjectNumber")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_projects_status");

                    b.ToTable("Projects", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Projects_Status", "[Status] IN ('Conceptual','Design','Bidding','Awarded','Procurement','Installation','Startup','Complete')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.ProjectDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobStorageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("DocumentId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_documents_project");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("ProjectId", "DocumentName", "Version")
                        .IsUnique()
                        .HasFilter("[Version] IS NOT NULL");

                    b.ToTable("ProjectDocuments", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_ProjectDocuments_DocumentType", "[DocumentType] IS NULL OR [DocumentType] IN ('Submittal','Drawing','Specification','Manual','Report','Other')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Rfi", b =>
                {
                    b.Property<Guid>("RfiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RFIId");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ResponseDate")
                        .HasColumnType("date");

                    b.Property<string>("RfiNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RFINumber");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("RfiId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("IssuedByUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RfiNumber")
                        .IsUnique();

                    b.ToTable("RFIs", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_RFIs_Status", "[Status] IS NULL OR [Status] IN ('Open','Acknowledged','InProgress','Responded','Closed')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AzureAdId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Company")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("UserId");

                    b.HasIndex("AzureAdId")
                        .IsUnique()
                        .HasFilter("[AzureAdId] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Admin','ProjectManager','Estimator','DesignEngineer','Technician','ServiceCoordinator','ContractorSuper','Client')");
                        });
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.ValveScheduleItem", b =>
                {
                    b.Property<Guid>("ValveScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActuatorType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pressure")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ValveTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ValveScheduleId");

                    b.HasIndex("ProjectId", "ValveTag")
                        .IsUnique();

                    b.ToTable("ValveSchedule", "dbo");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.ActivityLog", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Envora.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Controller", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.ControllerIoSlot", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.Point", "AssignedPoint")
                        .WithMany()
                        .HasForeignKey("AssignedPointId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Controller", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedPoint");

                    b.Navigation("Controller");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.DamperScheduleItem", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Deliverable", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Device", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Equipment", "MountedOnEquipment")
                        .WithMany()
                        .HasForeignKey("MountedOnEquipmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("MountedOnEquipment");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Equipment", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Job", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Envora.Api.Data.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Node", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.Controller", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Envora.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Controller");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Note", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Envora.Api.Data.Entities.Note", "ParentNote")
                        .WithMany()
                        .HasForeignKey("ParentNoteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Envora.Api.Data.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("ParentNote");

                    b.Navigation("Project");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.NoteReaction", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Envora.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Point", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.ControllerIoSlot", "ControllerIoSlot")
                        .WithMany()
                        .HasForeignKey("ControllerIOSlotId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Controller", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Controller");

                    b.Navigation("ControllerIoSlot");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Device");

                    b.Navigation("Equipment");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.PointDistribution", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.Controller", "ConsumingController")
                        .WithMany()
                        .HasForeignKey("ConsumingControllerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Envora.Api.Data.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Envora.Api.Data.Entities.Point", "SoftPoint")
                        .WithMany()
                        .HasForeignKey("SoftPointId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConsumingController");

                    b.Navigation("Node");

                    b.Navigation("Project");

                    b.Navigation("SoftPoint");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Project", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Company", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.User", "DesignEngineer1")
                        .WithMany()
                        .HasForeignKey("DesignEngineer1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.User", "DesignEngineer2")
                        .WithMany()
                        .HasForeignKey("DesignEngineer2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.Company", "EngineeringFirm")
                        .WithMany()
                        .HasForeignKey("EngineeringFirmId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.User", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("DesignEngineer1");

                    b.Navigation("DesignEngineer2");

                    b.Navigation("EngineeringFirm");

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.ProjectDocument", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Envora.Api.Data.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.Rfi", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Envora.Api.Data.Entities.User", "IssuedByUser")
                        .WithMany()
                        .HasForeignKey("IssuedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("IssuedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Envora.Api.Data.Entities.ValveScheduleItem", b =>
                {
                    b.HasOne("Envora.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
